Repository Metis-Team/mts_marker, pull requests merged in 2018-10, with the labels that each got.

#18 fix missing uav marker
  addons/markers/CfgMarkersBlufor.hpp
  addons/markers/CfgMarkersNeutral.hpp
  addons/markers/CfgMarkersRedfor.hpp
  addons/markers/CfgMarkersUnknown.hpp
Labels: bug fix

#10 Add Chinese Translate
  addons/markers/stringtable.xml
Labels: localization

#16 Add more markers
  addons/markers/CfgMarkersBlufor.hpp
  addons/markers/CfgMarkersNeutral.hpp
  addons/markers/CfgMarkersRedfor.hpp
  addons/markers/CfgMarkersUnknown.hpp
  addons/markers/data/blu/mod/mts_markers_blu_mod_amphibious.paa
  addons/markers/data/blu/mod/mts_markers_blu_mod_combined_arms.paa
  addons/markers/data/blu/mod/mts_markers_blu_mod_headquarters.paa
  addons/markers/data/blu/mod/mts_markers_blu_mod_joint_fire_support.paa
  addons/markers/data/blu/mod/mts_markers_blu_mod_naval.paa
  addons/markers/data/blu/mod/mts_markers_blu_mod_naval_top.paa
  addons/markers/data/blu/mod/mts_markers_blu_mod_special_forces.paa
  addons/markers/data/blu/mod/mts_markers_blu_mod_special_operation_forces.paa
  addons/markers/data/blu/mod/mts_markers_blu_mod_supply.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_amphibious.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_combined_arms.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_headquarters.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_joint_fire_support.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_naval.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_naval_top.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_special_forces.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_special_operation_forces.paa
  addons/markers/data/neu/mod/mts_markers_neu_mod_supply.paa
  addons/markers/data/red/mod/mts_markers_red_mod_amphibious.paa
  addons/markers/data/red/mod/mts_markers_red_mod_combined_arms.paa
  addons/markers/data/red/mod/mts_markers_red_mod_headquarters.paa
  addons/markers/data/red/mod/mts_markers_red_mod_joint_fire_support.paa
  addons/markers/data/red/mod/mts_markers_red_mod_naval.paa
  addons/markers/data/red/mod/mts_markers_red_mod_naval_top.paa
  addons/markers/data/red/mod/mts_markers_red_mod_special_forces.paa
  addons/markers/data/red/mod/mts_markers_red_mod_special_operation_forces.paa
  addons/markers/data/red/mod/mts_markers_red_mod_supply.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_amphibious_armor.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_amphibious_infantry.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_amphibious_reconnaissance.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_combined_arms.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_joint_fire_support.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_naval.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_special_forces.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_special_operation_forces.paa
  addons/markers/data/ui/icon/mts_markers_ui_icon_supply.paa
  addons/markers/data/ui/mod1/mts_markers_ui_mod1_headquarters.paa
  addons/markers/data/ui/mod1/mts_markers_ui_mod1_naval_top.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_amphibious.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_combined_arms.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_headquarters.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_joint_fire_support.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_naval.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_naval_top.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_special_forces.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_special_operation_forces.paa
  addons/markers/data/unk/mod/mts_markers_unk_mod_supply.paa
  addons/markers/initMarkerVariables.hpp
  addons/markers/stringtable.xml
Labels: enhancement

#15 Add the saving of the last selection
  addons/markers/XEH_preInit.sqf
  addons/markers/functions/fnc_createMarker.sqf
  addons/markers/functions/fnc_createMarkerLocal.sqf
  addons/markers/functions/fnc_initializeUI.sqf
  addons/markers/functions/fnc_setMarkerPreview.sqf
  addons/markers/functions/fnc_transmitUIData.sqf
  addons/markers/initKeybinds.hpp
  addons/markers/initSettings.hpp
  addons/markers/script_debug.hpp
  addons/markers/stringtable.xml
Labels: enhancement

#17 add copy paste functions
  addons/markers/XEH_PREP.hpp
  addons/markers/XEH_preInit.sqf
  addons/markers/functions/fnc_copyMarker.sqf
  addons/markers/functions/fnc_createMarkerLocal.sqf
  addons/markers/functions/fnc_pasteMarker.sqf
  addons/markers/initKeybinds.hpp
  addons/markers/stringtable.xml
Labels: enhancement

#20 fix channel selection & 3DEN key spamming
  addons/markers/functions/fnc_initializeUI.sqf
  addons/markers/initKeybinds.hpp
Labels: bug fix

#19 Optimize current channel retrieval
  addons/markers/functions/fnc_initializeUI.sqf
  addons/markers/functions/fnc_pasteMarker.sqf
  addons/markers/functions/fnc_transmitUIData.sqf
Labels: cleanup, enhancement

#21 optimize getDisplay
  addons/markers/functions/fnc_getDisplay.sqf
Labels: cleanup

#22 Add blocking of standard game actions
  addons/markers/functions/fnc_copyMarker.sqf
  addons/markers/functions/fnc_deleteMarker.sqf
  addons/markers/functions/fnc_moveMarkerMouseDown.sqf
  addons/markers/functions/fnc_pasteMarker.sqf
  addons/markers/initKeybinds.hpp
Labels: bug fix, cleanup
