Repository Metis-Team/mts_marker, pull requests merged in 2020-05, with the labels that each got.

#29 Add Korean translation
  addons/markers/stringtable.xml
Labels: localization

#30 Add contributors to Readme
  README.md
Labels: documentation

#28 Add version info in rpt
  addons/markers/XEH_preInit.sqf
Labels: enhancement
