Repository Metis-Team/mts_marker, pull requests merged in 2021-05, with the labels that each got.

#35 Replace CircleCI with Github Actions
  .circleci/config.yml
  .github/workflows/arma.yml
Labels: enhancement

#36 Use ACE version of sqf validator
  tools/sqf_validator.py
Labels: enhancement

#34 Handle 3DEN keybinds over CBA keybindings
  addons/markers/XEH_PREP.hpp
  addons/markers/XEH_preInit.sqf
  addons/markers/functions/fnc_3denKeyHandler.sqf
  addons/markers/functions/fnc_3denMouseHandler.sqf
  addons/markers/init3denKeybinds.hpp
  addons/markers/initKeybinds.hpp
  addons/markers/script_component.hpp
  addons/markers/stringtable.xml
Labels: documentation, enhancement

#37 change faq to cba defaults #34
  README.md
Labels: documentation
